version: '3'

services:
    web:
        build: ./docker/php-fpm
        ports:
          - 8000:80
        volumes:
            - ./:/var/www/html

    composer:
         build: ./docker/php-fpm
         entrypoint: composer
         command: install --no-dev
         volumes:
            - ./:/var/www/html

    database:
        image: mariadb:latest
        volumes:
          - database:/var/lib/mysql

        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: home

    adminer:
        image: adminer:latest
        ports:
            - 8090:80
        links:
            - database:db

    elasticsearch:
        build: ./docker/elastic
        environment:
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - xpack.security.enabled=false
        ports:
            - "9200:9200"
        networks:
            - elastic

    kibana:
        image: docker.elastic.co/kibana/kibana:5.6.2
        ports:
            - "5601:5601"
        networks:
            - elastic
        depends_on:
            - elasticsearch

#    cerebro:
#        image: yannart/cerebro:0.6.6
#        ports:
#            - "9000:9000"
#        networks:
#            - elastic
#        depends_on:
#            - elasticsearch

    logstash:
        build: ./docker/logstash
        ports:
            - "9001:9001"
        volumes:
            - ~/Code/home-control/docker/logstash/pipeline/:/usr/share/logstash/pipeline/
        networks:
            - elastic
        depends_on:
            - elasticsearch

networks:
    elastic:
        driver: bridge

volumes:
    database:

#docker run --rm -it  -v ~/Code/home-control/docker/logstash/pipeline/:/usr/share/logstash/pipeline/ --network homecontrol_elastic docker.elastic.co/logstash/logstash:5.6.2
#docker run --rm -it  -v ~/Code/home-control/docker/logstash/pipeline/:/usr/share/logstash/pipeline/ --network homecontrol_elastic docker.elastic.co/logstash/logstash:5.6.2
