version: '3'

services:
    web:
        build: ./docker/php-fpm
        ports:
          - 8000:80
        volumes:
            - ./:/var/www/html

    composer:
         build: ./docker/php-fpm
         entrypoint: composer
         command: install --no-dev
         volumes:
            - ./:/var/www/html

    database:
        image: mariadb:latest
        volumes:
          - database:/var/lib/mysql

        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: home

    adminer:
        image: adminer:latest
        ports:
            - 8090:80
        links:
            - database:db

volumes:
    database:
